### ISSUE TITLE
v0.4.0 release throws unexpected keyword argument 'verbose' error

### ISSUE THREAD

**Issue by RahulPrasad** [jerryjliu/gpt_index#410]
Latest release now throws a TypeError: __init__() got an unexpected keyword argument 'verbose'.

Sample code that worked with previous version 0.3.6:

```
GPTSimpleVectorIndex(
        documents, llm_predictor=llm_predictor, prompt_helper=prompt_helper, verbose=True
    )
```

Any suggestions on what I need to change for it to work with new version?

**Comment by jerryjliu** [comment]
there are no more `verbose` parameters anywhere

**Comment by jerryjliu** [comment]
take a look at this section for getting outputs in a jupyter notebook instead: https://gpt-index.readthedocs.io/en/latest/getting_started/starter_example.html#viewing-queries-and-events-using-logging

**Comment by RahulPrasad** [comment]
ah ha, this is much neater approach. Thanks!
